### PR TITLE
Add install,sh

### PR DESCRIPTION
**Pull request by PTFOPlayer**
Add simpler way of installing

### CODE REVIEW

**Review by Fir3Storm31 — APPROVED** [review]

**Comment by Plippo** [comment]
I've extended the script so it can also uninstall the previous version. I also changed it so it can be run as root and we don't need all those sudos anymore (so you now have to run the script using `sudo sh install.sh` but it simplifies the script).

**Comment by Fir3Storm31** [comment]
I implemented the changes so far with the check and download of the "patch" package and the "prepare-for-current-kernel.sh" script in the new pull request #53

**Review by PTFOPlayer — COMMENTED** [review]
that looks a lot better than mine

**Comment by Plippo** [comment]
So I'm closing this PR, further work is carried out in PR #53.

**Pull request closed without merging**
