### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by simonchen007**
fix issue #25

### CODE REVIEW

**Comment by Plippo** [comment]
@simonchen007 Can you explain this change? I don't see why calling depmod should help after the module has already been built.

**Comment by Plippo** [comment]
@simonchen007 Can you explain why this is needed? `dkms install` already calls `depmod` as far as I know.

**Comment by simonchen007** [comment]
@Plippo  Thing is that, the origin Kernel(5.8.x) already have these drivers(/lib/modules/YOURKERNELVERSION/kernel/drivers/platform/x86/asus-nb-wmi.ko , and /lib/modules/YOURKERNELVERSION/kernel/drivers/platform/x86/asus-wmi.ko ), so, I have to remove those, and rerun depmod, or it would not works after reboot.

**Comment by Plippo** [comment]
But in this pull request only the depmod is added, without removing the modules first. I'd rather add an addendum to the readme that says "If you have problems that the new version of the module is not used after a reboot, you can do the following..." and then a complete description of what to do in addition to running depmod.

**Comment by simonchen007** [comment]
okay, I will add it, and send a PR again.
I found anohter 2 issues , 
1. once the system goes suspend, the main screen will go off. but the screenpad just "no display" but the backlight still existing. Do you have solution  for that ?
2.  the backlight of the keyboard won't go disable.

**Comment by Plippo** [comment]
> I found anohter 2 issues ,
> 
>     1. once the system goes suspend, the main screen will go off. but the screenpad just "no display" but the backlight still existing.
> 
>     2. the backlight of the keyboard won't go disable.
> 
> 
> Do you have solution for those ?

I'm afraid neither of those problems exist on my model, so unfortunately I can't provide you with a solution.

**Comment by simonchen007** [comment]
The linux mint upgraded the kernel as 5.11.0-25-generic , this module seems do not works currently

**Comment by kevinchappell** [comment]
@simonchen007 i got the same kernel version through update on ubuntu and the module stopped working.

To get it working again i reinstalled module and reinstalled the kernel
```
sudo apt install --reinstall linux-image-$(uname -r)
```

i have no idea why it worked in that order!

---


> 1. once the system goes suspend, the main screen will go off. but the screenpad just "no display" but the backlight still existing.

I have this semi-solved with 2 scripts on UX482 running Ubuntu with Gnome DE

1. Previously I had only [this script](https://gist.github.com/kevinchappell/a0e3ec7fb5a073b58b8433a7164cdc7a) running as a service that would listen for lock events and disable the screenpad. However disabling the screenpad after lock would wake the other screen
1. So I added a custom keybinding for the screenpad button to call a script that disables the screenpad _then_ locks the computer. The first script will turn it back on on unlock.

*key binding*
```
[custom4]
binding='Launch7'
command='$HOME/bin/screenpad-key-lock.sh'
name='lock screen'
```

*screenpad-key-lock.sh*
```
#!/bin/bash
echo 0 | tee '/sys/class/leds/asus::screenpad/brightness'
dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
```

**Comment by simonchen007** [comment]
@kevinchappell  The point is  ```/sys/class/leds/asus::screenpad/``` is disappeared after upgraded to 5.11 , I have role back to 5.8 .
Thanks for your scripts.

**Review by Plippo — APPROVED** [review]

**Pull request merged**
